# Generated by Django 5.1.15 on 2026-09-24 19:02

import apps.tuition_jobs.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, default=apps.tuition_jobs.models.generate_job_id, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(default='Dhaka', max_length=100)),
                ('area', models.CharField(default='Mirpur', max_length=100)),
                ('student_gender', models.CharField(default='Male', max_length=20)),
                ('preferred_tutor_gender', models.CharField(choices=[('Any', 'Any Tutor'), ('Male', 'Male Tutor Only'), ('Female', 'Female Tutor Only')], default='Any', max_length=20)),
                ('curriculum', models.CharField(default='English Version', max_length=100)),
                ('class_level', models.CharField(default='Class 9', max_length=100)),
                ('subjects', models.JSONField(default=list)),
                ('days_per_week', models.PositiveIntegerField(default=3)),
                ('tutoring_time', models.CharField(default='5:30 PM - 7:00 PM', max_length=100)),
                ('salary', models.PositiveIntegerField(default=8000)),
                ('tuition_type', models.CharField(default='Home Tutoring', max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SHORTLISTED', 'Shortlisted'), ('APPOINTED', 'Appointed'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=20)),
                ('requirements_text', models.TextField(blank=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
