# Generated by Django 5.1.15 on 2026-10-03 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionjob',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='tuitionjob',
            old_name='parent',
            new_name='student',
        ),
    ]
