# Generated by Django 5.1.15 on 2026-09-24 19:02

import apps.requirements.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorRequirement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_id', models.CharField(db_index=True, default=apps.requirements.models.generate_requirement_id, max_length=20, unique=True)),
                ('parent_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('student_name', models.CharField(max_length=150)),
                ('student_gender', models.CharField(default='Female', max_length=20)),
                ('city', models.CharField(default='Dhaka', max_length=100)),
                ('area', models.CharField(default='Dhanmondi', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('curriculum', models.CharField(default='English Version', max_length=100)),
                ('class_level', models.CharField(default='Class 10 (SSC)', max_length=100)),
                ('subjects', models.JSONField(default=list)),
                ('preferred_tutor_gender', models.CharField(default='Any', max_length=20)),
                ('days_per_week', models.PositiveIntegerField(default=3)),
                ('preferred_time', models.CharField(default='5:00 PM - 7:00 PM', max_length=100)),
                ('budget', models.PositiveIntegerField(default=9000)),
                ('additional_requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Tutor Assignment'), ('MATCHED', 'Tutors Matched'), ('TUTOR_SELECTED', 'Tutor Selected for Trial'), ('COMPLETED', 'Tuition Active'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('selected_tutor_id', models.CharField(blank=True, max_length=50)),
                ('matched_tutors', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
