# Generated by Django 5.1.15 on 2026-09-24 19:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('institution_or_location', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('PARENT', 'Guardian / Parent'), ('TUTOR', 'Verified Tutor'), ('STAKEHOLDER', 'Academic Stakeholder')], default='PARENT', max_length=20)),
                ('avatar', models.URLField(max_length=500)),
                ('video_thumbnail', models.URLField(blank=True, max_length=500)),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
