# Generated by Django 5.1.15 on 2026-09-24 19:02

import apps.affiliates.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatePartner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(default='Student Ambassador', max_length=150)),
                ('institution', models.CharField(default='BUET', max_length=200)),
                ('referral_code', models.CharField(default=apps.affiliates.models.generate_referral_code, max_length=30, unique=True)),
                ('total_referrals', models.PositiveIntegerField(default=0)),
                ('successful_matches', models.PositiveIntegerField(default=0)),
                ('commission_rate', models.PositiveIntegerField(default=10, help_text='Commission percentage %')),
                ('total_earnings', models.PositiveIntegerField(default=0)),
                ('pending_payout', models.PositiveIntegerField(default=0)),
                ('payout_method', models.CharField(default='bKash', max_length=50)),
                ('payout_account_number', models.CharField(blank=True, max_length=50)),
                ('is_approved', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_earnings', '-created_at'],
            },
        ),
    ]
