# Generated by Django 5.1.15 on 2026-10-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TUTOR', 'Tutor'), ('STUDENT', 'Student'), ('ADMIN', 'Admin')], default='TUTOR', max_length=20),
        ),
    ]
