# Generated by Django 5.1.15 on 2026-10-03 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='is_verified_guardian',
            new_name='is_verified_student',
        ),
        migrations.RemoveField(
            model_name='review',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='review',
            name='guardian_name',
        ),
        migrations.AddField(
            model_name='review',
            name='ai_sentiment',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='review',
            name='ai_strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='review',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='student',
            field=models.ForeignKey(blank=True, db_column='guardian_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='student_name',
            field=models.CharField(default='Anonymous Student', max_length=150),
        ),
    ]
