# Generated by Django 5.1.15 on 2026-09-24 19:02

import apps.tutors.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tutor_id', models.CharField(db_index=True, default=apps.tutors.models.generate_tutor_id, max_length=20, unique=True)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10)),
                ('university', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('degree_title', models.CharField(default='B.Sc Engineering', max_length=200)),
                ('passing_year', models.CharField(default='2024', max_length=20)),
                ('cgpa', models.CharField(default='3.85 / 4.00', max_length=50)),
                ('city', models.CharField(default='Dhaka', max_length=100)),
                ('area', models.CharField(default='Mirpur', max_length=100)),
                ('expected_salary', models.PositiveIntegerField(default=8000)),
                ('experience_years', models.PositiveIntegerField(default=2)),
                ('subjects', models.JSONField(default=list, help_text='List of teaching subjects')),
                ('classes', models.JSONField(default=list, help_text='List of targeted class levels')),
                ('curriculums', models.JSONField(default=list, help_text='NCTB Bangla, English Version, Edexcel, Cambridge')),
                ('preferred_locations', models.JSONField(default=list, help_text='Preferred tutoring areas')),
                ('tutoring_types', models.JSONField(default=list, help_text='Home Tutoring, Online Tutoring, Group Tutoring')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_tuitions_completed', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('nid_or_birth_cert', models.CharField(blank=True, max_length=50)),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='tutor_docs/')),
                ('profile_photo_url', models.URLField(blank=True, max_length=500)),
                ('profile_completion_score', models.PositiveIntegerField(default=85)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', '-is_verified', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('institution_or_platform', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_records', to='tutors.tutorprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TutorEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('passing_year', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=50)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_records', to='tutors.tutorprofile')),
            ],
            options={
                'ordering': ['-passing_year'],
            },
        ),
    ]
