# Generated by Django 5.1.15 on 2026-09-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='university',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
